fieldLayouts:
  3aa53c8a-56b4-4526-8996-ab57b9465dc7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db3c02a1-3b0e-4610-a9bb-ac520803feec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9429f60-04db-49ee-9942-9cb0a6494ab9
        userCondition: null
handle: homePage
hasTitleField: false
name: 'Home Page'
section: 85f7820d-ba64-48d7-9114-08e3de79222d # Home Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
