fieldLayouts:
  17b89560-3d48-45eb-93c5-26f1bd997b65:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6b6ecf5c-b1dd-4f52-bd2a-e41906a77797 # Time Label
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70dbe5d8-6c97-4514-9066-c1d121f8bd84 # Session Type
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9536067d-c794-497b-977b-83252c95af94 # Description
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7fc45f38-3a88-4652-ab2e-0e6bac5e3779 # Speaker
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Session Fields'
        sortOrder: 1
handle: session
hasTitleField: true
name: Session
section: e985d336-b545-4c61-a2f6-5c5fba1ab083 # Session
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
