defaultPlacement: end
fieldLayouts:
  c803f8b4-f9ac-4bdd-8e59-bfb732e22ef2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: f93a4876-6deb-4bcc-8309-5a3250b953a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5457000e-08aa-4f1a-8762-5984219739a9
        userCondition: null
handle: sessionTypes
name: 'Session Types'
siteSettings:
  55cfac3d-0c99-45c7-a9df-cfb0299201e6: # Method Conf
    hasUrls: true
    template: session-types/_category
    uriFormat: 'session-types/{slug}'
structure:
  maxLevels: 1
  uid: 004913d8-d70c-43ff-95f3-d7a6ff770683
