categoryGroups:
  e23f857a-b75c-47ea-959b-ce61589c89f8:
    name: 'Session Types'
    handle: sessionTypes
    structure:
      uid: 004913d8-d70c-43ff-95f3-d7a6ff770683
      maxLevels: 1
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        hasUrls: true
        uriFormat: 'session-types/{slug}'
        template: session-types/_category
dateModified: 1580572926
email:
  fromEmail: president@sgf.dev
  fromName: 'Method Conf'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa:
    name: 'Speaker Fields'
  7bc3d583-a86f-457a-b97a-0ba8d1711bf1:
    name: 'Sponsor Fields'
  abfcb8b1-ecb6-44c0-885f-1e7dd29b1953:
    name: Common
  d64a3f4b-1126-4c94-8c00-6792255b93f3:
    name: 'Session Fields'
fields:
  151106e8-460f-4c27-968a-ee7e7a208172:
    name: 'Professional Title'
    handle: professionalTitle
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  42dd3c37-b6b6-450d-84b3-ecd03f7fe859:
    name: 'Mobile Sponsor'
    handle: mobileSponsor
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\Lightswitch
    settings:
      default: ''
    contentColumnType: boolean
    fieldGroup: 7bc3d583-a86f-457a-b97a-0ba8d1711bf1
  466cdddf-d46c-45fd-88d1-333d6e5cf248:
    name: 'Github URL'
    handle: githubUrl
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  624394ce-bb4a-4e0a-8154-e7bc6371da79:
    name: Bio
    handle: bio
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  68729a64-08f9-43fe-b05b-9959dbff0c21:
    name: 'Website URL'
    handle: websiteUrl
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  6b6ecf5c-b1dd-4f52-bd2a-e41906a77797:
    name: 'Time Label'
    handle: timeLabel
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: d64a3f4b-1126-4c94-8c00-6792255b93f3
    contentColumnType: text
  70dbe5d8-6c97-4514-9066-c1d121f8bd84:
    name: 'Session Type'
    handle: sessionType
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Categories
    settings:
      branchLimit: '1'
      sources: '*'
      source: 'group:e23f857a-b75c-47ea-959b-ce61589c89f8'
      targetSiteId: null
      viewMode: null
      limit: null
      selectionLabel: 'Set Session Type'
      localizeRelations: false
    fieldGroup: d64a3f4b-1126-4c94-8c00-6792255b93f3
    contentColumnType: string
  72363ca7-2a79-4a61-a970-53589df167ae:
    name: Background
    handle: sponsorBackground
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\RadioButtons
    settings:
      options:
        -
          label: Light
          value: light
          default: '1'
        -
          label: Dark
          value: dark
          default: ''
    fieldGroup: 7bc3d583-a86f-457a-b97a-0ba8d1711bf1
    contentColumnType: string
  776d50aa-32ed-43ec-8217-4d36b3d9ca3b:
    name: 'Page Content'
    handle: pageContent
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
    fieldGroup: abfcb8b1-ecb6-44c0-885f-1e7dd29b1953
    contentColumnType: text
  7fc45f38-3a88-4652-ab2e-0e6bac5e3779:
    name: Speaker
    handle: speaker
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Entries
    settings:
      sources:
        - 'section:e89bcf47-f993-48a1-a261-492a199be1bd'
      source: null
      targetSiteId: null
      viewMode: null
      limit: '1'
      selectionLabel: 'Set Speaker'
      localizeRelations: false
    fieldGroup: d64a3f4b-1126-4c94-8c00-6792255b93f3
    contentColumnType: string
  9536067d-c794-497b-977b-83252c95af94:
    name: Description
    handle: description
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\redactor\Field
    settings:
      redactorConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      columnType: text
      availableVolumes: '*'
      availableTransforms: '*'
      removeInlineStyles: '1'
      removeEmptyTags: '1'
      removeNbsp: '1'
    fieldGroup: d64a3f4b-1126-4c94-8c00-6792255b93f3
    contentColumnType: text
  9bae2cf5-a626-476a-a0b7-fb984823e57a:
    name: 'LinkedIn URL'
    handle: linkedinUrl
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  a174c740-f259-401e-8203-f522b28763ea:
    name: 'Twitter2 URL'
    handle: twitter2Url
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  c9de1bd4-11ed-4eab-9d41-5f074df8d40f:
    name: 'Twitter URL'
    handle: twitterUrl
    instructions: ''
    searchable: true
    translationMethod: none
    translationKeyFormat: null
    type: craft\fields\PlainText
    settings:
      placeholder: ''
      code: ''
      multiline: ''
      initialRows: '4'
      charLimit: ''
      columnType: text
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: text
  e9ca620d-c061-47f8-ae05-5f28de79ab8a:
    name: Image
    handle: image
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:3b75095c-c375-4b83-b48c-3238aa0472d1'
      defaultUploadLocationSubpath: speakers
      singleUploadLocationSource: 'volume:3b75095c-c375-4b83-b48c-3238aa0472d1'
      singleUploadLocationSubpath: speakers
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Add Speaker Image'
      localizeRelations: false
    fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
    contentColumnType: string
  ff251cf3-747b-4dab-b959-d30e55554df8:
    name: 'Sponsor Image'
    handle: sponsorImage
    instructions: ''
    searchable: true
    translationMethod: site
    translationKeyFormat: null
    type: craft\fields\Assets
    settings:
      useSingleFolder: '1'
      defaultUploadLocationSource: 'volume:3b75095c-c375-4b83-b48c-3238aa0472d1'
      defaultUploadLocationSubpath: ''
      singleUploadLocationSource: 'volume:3b75095c-c375-4b83-b48c-3238aa0472d1'
      singleUploadLocationSubpath: sponsors
      restrictFiles: '1'
      allowedKinds:
        - image
      sources: '*'
      source: null
      targetSiteId: null
      viewMode: large
      limit: '1'
      selectionLabel: 'Add Sponsor Image'
      localizeRelations: false
    fieldGroup: 7bc3d583-a86f-457a-b97a-0ba8d1711bf1
    contentColumnType: string
globalSets:
  dd6ca768-6d95-4de3-8e3e-133bcdf83452:
    name: Meta
    handle: meta
plugins:
  element-api:
    settings: null
    licenseKey: null
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    settings: null
    licenseKey: null
    enabled: true
    schemaVersion: 2.3.0
sections:
  385f8afb-ae4d-48e1-ab4d-044ea815d451:
    name: Page
    handle: page
    type: structure
    enableVersioning: true
    structure:
      uid: 097bd686-913c-4f07-8f51-193aef38d36f
      maxLevels: null
    entryTypes:
      c6c8fc5f-8358-4a21-8e10-44d032de5b0f:
        name: Page
        handle: page
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
        fieldLayouts:
          22d06e4b-261b-407e-9d38-22331a761ffb:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  776d50aa-32ed-43ec-8217-4d36b3d9ca3b:
                    required: false
                    sortOrder: 1
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: '{parent.uri}/{slug}'
        template: page.twig
    propagationMethod: all
  5cd67bde-12a3-411c-a156-199fc34c7e80:
    name: Sponsors
    handle: sponsors
    type: structure
    enableVersioning: true
    structure:
      uid: 5ce571f6-bd4b-46f2-9918-697f4769c0e6
      maxLevels: 1
    entryTypes:
      b8e9493f-b388-4a6c-b8fc-0fd4ac09d75e:
        name: Sponsors
        handle: sponsors
        hasTitleField: true
        titleLabel: Title
        titleFormat: ''
        sortOrder: 1
        fieldLayouts:
          4a201fe5-f498-4c5a-9e6a-4a76b2ec1120:
            tabs:
              -
                name: Content
                sortOrder: 1
                fields:
                  42dd3c37-b6b6-450d-84b3-ecd03f7fe859:
                    required: false
                    sortOrder: 4
                  68729a64-08f9-43fe-b05b-9959dbff0c21:
                    required: false
                    sortOrder: 2
                  72363ca7-2a79-4a61-a970-53589df167ae:
                    required: false
                    sortOrder: 3
                  ff251cf3-747b-4dab-b959-d30e55554df8:
                    required: false
                    sortOrder: 1
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'sponsors/{slug}'
        template: sponsors/_entry
    propagationMethod: all
  85f7820d-ba64-48d7-9114-08e3de79222d:
    name: 'Home Page'
    handle: homePage
    type: single
    enableVersioning: true
    entryTypes:
      1d93a068-4774-49ad-960a-1a2d14ea6121:
        name: 'Home Page'
        handle: homePage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: home.twig
    propagationMethod: all
  e89bcf47-f993-48a1-a261-492a199be1bd:
    name: Speaker
    handle: speaker
    type: channel
    enableVersioning: true
    entryTypes:
      7e355fce-5f03-4b13-8de8-b23c7f4689d1:
        name: Speaker
        handle: speaker
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
        fieldLayouts:
          81616812-777a-4cf9-ba90-1244c57330c4:
            tabs:
              -
                name: 'Speaker Fields'
                sortOrder: 1
                fields:
                  151106e8-460f-4c27-968a-ee7e7a208172:
                    required: false
                    sortOrder: 2
                  466cdddf-d46c-45fd-88d1-333d6e5cf248:
                    required: false
                    sortOrder: 5
                  624394ce-bb4a-4e0a-8154-e7bc6371da79:
                    required: false
                    sortOrder: 3
                  68729a64-08f9-43fe-b05b-9959dbff0c21:
                    required: false
                    sortOrder: 4
                  9bae2cf5-a626-476a-a0b7-fb984823e57a:
                    required: false
                    sortOrder: 8
                  a174c740-f259-401e-8203-f522b28763ea:
                    required: false
                    sortOrder: 7
                  c9de1bd4-11ed-4eab-9d41-5f074df8d40f:
                    required: false
                    sortOrder: 6
                  e9ca620d-c061-47f8-ae05-5f28de79ab8a:
                    required: false
                    sortOrder: 1
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'speaker/{slug}'
        template: speaker.twig
    propagationMethod: all
  e985d336-b545-4c61-a2f6-5c5fba1ab083:
    name: Session
    handle: session
    type: structure
    enableVersioning: true
    structure:
      uid: 051f77ca-9bdb-47e5-bf0f-9565776f847c
      maxLevels: 1
    entryTypes:
      c67b8f57-8258-4a8d-a164-275fd79b7345:
        name: Session
        handle: session
        hasTitleField: true
        titleLabel: Title
        titleFormat: null
        sortOrder: 1
        fieldLayouts:
          17b89560-3d48-45eb-93c5-26f1bd997b65:
            tabs:
              -
                name: 'Session Fields'
                sortOrder: 1
                fields:
                  6b6ecf5c-b1dd-4f52-bd2a-e41906a77797:
                    required: false
                    sortOrder: 1
                  70dbe5d8-6c97-4514-9066-c1d121f8bd84:
                    required: false
                    sortOrder: 2
                  7fc45f38-3a88-4652-ab2e-0e6bac5e3779:
                    required: false
                    sortOrder: 4
                  9536067d-c794-497b-977b-83252c95af94:
                    required: false
                    sortOrder: 3
    siteSettings:
      55cfac3d-0c99-45c7-a9df-cfb0299201e6:
        enabledByDefault: true
        hasUrls: true
        uriFormat: 'session/{slug}'
        template: session/_entry
    propagationMethod: all
siteGroups:
  40402c41-068c-4a6d-badf-cfb25d9de87c:
    name: 'Method Conf'
sites:
  55cfac3d-0c99-45c7-a9df-cfb0299201e6:
    name: 'Method Conf'
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: '@web/'
    sortOrder: 1
    primary: true
    siteGroup: 40402c41-068c-4a6d-badf-cfb25d9de87c
system:
  edition: solo
  live: true
  name: 'Method Conf'
  timeZone: America/Los_Angeles
  schemaVersion: 3.3.3
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  3b75095c-c375-4b83-b48c-3238aa0472d1:
    name: 'Local Volume'
    handle: localVolume
    type: craft\volumes\Local
    hasUrls: true
    url: '@web/uploads'
    settings:
      path: '@webroot/uploads'
    sortOrder: 1
