fieldLayouts:
  bb569799-e948-423d-9893-950e77a6626e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c90514fc-7dca-4004-a643-ce81007605aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40ab4808-fb71-49a2-a524-e698167a1753
        userCondition: null
fs: localVolume
handle: localVolume
name: 'Local Volume'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
