columnSuffix: null
handle: description
instructions: null
name: Description
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: b6539371-ce4c-4185-8dd9-04a263e8cb2a # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
