columnSuffix: null
handle: mobileSponsor
instructions: null
name: 'Mobile Sponsor'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
