columnSuffix: null
contentColumnType: text
fieldGroup: abfcb8b1-ecb6-44c0-885f-1e7dd29b1953 # Common
handle: pageContent
instructions: null
name: 'Page Content'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: b6539371-ce4c-4185-8dd9-04a263e8cb2a # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
