columnSuffix: null
contentColumnType: text
fieldGroup: 2577dfee-5ef6-4a1b-bcd1-93f55efbf4fa
handle: professionalTitle
instructions: ''
name: 'Professional Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
