columnSuffix: null
contentColumnType: string
fieldGroup: 7bc3d583-a86f-457a-b97a-0ba8d1711bf1 # Sponsor Fields
handle: sponsorBackground
instructions: null
name: Background
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Light
        -
          - value
          - light
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - dark
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
