columnSuffix: null
contentColumnType: text
fieldGroup: d64a3f4b-1126-4c94-8c00-6792255b93f3
handle: timeLabel
instructions: ''
name: 'Time Label'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
