defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  55cfac3d-0c99-45c7-a9df-cfb0299201e6:
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
