defaultPlacement: end
enableVersioning: true
entryTypes:
  - c6c8fc5f-8358-4a21-8e10-44d032de5b0f # Page
handle: page
maxAuthors: 1
name: Page
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  55cfac3d-0c99-45c7-a9df-cfb0299201e6: # Method Conf
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 097bd686-913c-4f07-8f51-193aef38d36f
type: structure
