defaultPlacement: end
enableVersioning: true
handle: speaker
name: Speaker
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  55cfac3d-0c99-45c7-a9df-cfb0299201e6:
    enabledByDefault: true
    hasUrls: true
    template: speaker.twig
    uriFormat: 'speaker/{slug}'
type: channel
